services:
  - type: web
    name: ultimate-frisbee-manager-api
    env: node
    buildCommand: cd backend && npm install --include=dev && npm run deploy:render
    startCommand: cd backend && npm start
    plan: free
    region: frankfurt
    rootDir: ./
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: NODE_ENV
        value: production
      - key: CORS_ORIGINS
        value: https://ultimate-frisbee-manager-kinder.vercel.app,http://localhost:4200
      - key: JWT_SECRET
        fromSecret: jwt-secret
      - key: JWT_REFRESH_SECRET
        fromSecret: jwt-refresh-secret
      - key: CLOUDINARY_URL
        fromSecret: cloudinary-url

databases:
  - name: ultimate-frisbee-manager-db
    plan: free
    region: frankfurt
